# Generated by Django 3.1.1 on 2020-12-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20201206_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesave',
            name='upload',
            field=models.FileField(default=True, upload_to='projectimg/'),
        ),
    ]
