# Generated by Django 3.1.1 on 2020-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201206_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesave',
            name='upload',
            field=models.ImageField(blank=True, upload_to='OCR_detection/static'),
        ),
    ]
