# Generated by Django 3.1.1 on 2020-12-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20201207_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesave',
            name='upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
