# Generated by Django 3.1.1 on 2020-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_auto_20201207_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('qualification', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Signup Data',
            },
        ),
    ]
