# Generated by Django 3.1.1 on 2020-12-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_signupdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesave',
            name='upload',
            field=models.ImageField(upload_to='OCR_detection/static/new_img'),
        ),
    ]
