# Generated by Django 3.1.1 on 2020-12-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_filesave'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocxSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_docx', models.FileField(upload_to='OCR_detection/static/new_docx')),
            ],
            options={
                'db_table': 'Pdf Upload',
            },
        ),
        migrations.CreateModel(
            name='PdfSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pdf', models.FileField(upload_to='OCR_detection/static/new_pdf')),
            ],
            options={
                'db_table': 'Docx Upload',
            },
        ),
        migrations.DeleteModel(
            name='FileSave',
        ),
    ]
