# Generated by Django 3.1.1 on 2021-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_auto_20201212_0825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupData',
        ),
    ]
