# Generated by Django 3.1.1 on 2021-05-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_delete_signupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='docxsave',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='imagesave',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pdfsave',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
